### ISSUE TITLE
3_train.py 'conv_hyperparams_fn'

### ISSUE THREAD

**Issue by tigon7476** [MicrocontrollersAndMore/TensorFlow_Tut_3_Object_Detection_Walk-through#3]
Hello, thank you very much for your tutorials, however I just caught an error. 
I downloaded tensorflow/models yesterday, ran 3_train.py and caught this error. 
Before about 1 month, there was no error.

C:\Python\Python36\python.exe C:/Users/Admin/Documents/cris_dahms/TensorFlow_Tut_3_Object_Detection_Walk-through/3_train.py
WARNING:tensorflow:From C:\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
starting program . . .
Traceback (most recent call last):
  File "C:/Users/Admin/Documents/cris_dahms/TensorFlow_Tut_3_Object_Detection_Walk-through/3_train.py", line 153, in <module>
    tf.app.run()
  File "C:\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:/Users/Admin/Documents/cris_dahms/TensorFlow_Tut_3_Object_Detection_Walk-through/3_train.py", line 115, in main
    CLONE_ON_CPU, ps_tasks, worker_job_name, is_chief, TRAINING_DATA_DIR)
  File "C:\TensorFlow\models\research\object_detection\trainer.py", line 240, in train
    detection_model = create_model_fn()
  File "C:\TensorFlow\models\research\object_detection\builders\model_builder.py", line 98, in build
    add_background_class)
  File "C:\TensorFlow\models\research\object_detection\builders\model_builder.py", line 166, in _build_ssd_model
    is_training=is_training)
  File "C:\TensorFlow\models\research\object_detection\builders\model_builder.py", line 138, in _build_ssd_feature_extractor
    override_base_feature_extractor_hyperparams)
  File "C:\TensorFlow\models\research\object_detection\models\ssd_inception_v2_feature_extractor.py", line 68, in __init__
    raise ValueError('SSD Inception V2 feature extractor always uses'
ValueError: SSD Inception V2 feature extractor always usesscope returned by `conv_hyperparams_fn` for both the base feature extractor and the additional layers added since there is no arg_scope defined for the base feature extractor.

Process finished with exit code 1

**Comment by MicrocontrollersAndMore** [comment]
I just re-ran everything from the beginning and I received the same error.  Probably something in TensorFlow models has changed, I'll have to look into it this weekend . . .﻿

**Comment by tigon7476** [comment]
Thank you for your reply.I ''ll wait for your answer^&^


삼성 갤럭시 스마트폰에서 보냈습니다.
-------- 원본 이메일 --------보낸 사람: Chris Dahms <notifications@github.com> 날짜: 18/4/25  오후 6:11  (GMT+08:00) 받은 사람: MicrocontrollersAndMore/TensorFlow_Tut_3_Object_Detection_Walk-through <TensorFlow_Tut_3_Object_Detection_Walk-through@noreply.github.com> 참조: tigon7476 <tigon7476@naver.com>, Author <author@noreply.github.com> 제목: Re: [MicrocontrollersAndMore/TensorFlow_Tut_3_Object_Detection_Walk-through] 3_train.py 'conv_hyperparams_fn' (#3) 
I just re-ran everything from the beginning and I received the same error.  Probably something in TensorFlow models has changed, I'll have to look into it this weekend . . .﻿

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrocontrollersAndMore/TensorFlow_Tut_3_Object_Detection_Walk-through","title":"MicrocontrollersAndMore/TensorFlow_Tut_3_Object_Detection_Walk-through","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrocontrollersAndMore/TensorFlow_Tut_3_Object_Detection_Walk-through"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MicrocontrollersAndMore in #3: I just re-ran everything from the beginning and I received the same error.  Probably something in TensorFlow models has changed, I'll have to look into it this weekend . . .﻿"}],"action":{"name":"View Issue","url":"https://github.com/MicrocontrollersAndMore/TensorFlow_Tut_3_Object_Detection_Walk-through/issues/3#issuecomment-384235666"}}}

**Comment by MicrocontrollersAndMore** [comment]
This is by no means a permanent fix, but for now, open the file "C:\TensorFlow\models\research\object_detection\models" and comment out lines 67-72 like this:

![untitled1](https://user-images.githubusercontent.com/5672876/39262419-56a42ebc-488d-11e8-851b-8ca069f39ffe.png)

You will get a bunch of warnings during training:

![untitled2](https://user-images.githubusercontent.com/5672876/39262565-bb1a637a-488d-11e8-812b-05436eb192d0.png)

But the object detection still worked at the end of the process.

Eventually I'll figure out what changed and work out a permanent fix.

**Comment by mkparacha** [comment]
Dear, I need help in a project for Vehicle number recognition from 2 MP IP camera. my email is mkamranparacha@yahoo.com

Pls contact ASAP

**Comment by haroonshahzad786** [comment]
i am getting this output with error!
starting program . . .
error: Please upgrade your tensorflow installation to v1.5.* or later!

**Comment by shashank2710** [comment]
@haroonshahzad786 . Check your version of Tensorflow. If it is higher than 1.5 and you are still getting this error, kindly comment out the lines in the code which checks for version.
